name: ExtDN Unit Tests
on: [push]

jobs:
  unit-tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    env:
      MODULE_NAME: ${{ secrets.MODULE_NAME }}
      COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-unit-tests/7.3@master
        env:
          MAGENTO_VERSION: '2.3.6'
      - uses: extdn/github-actions-m2/magento-unit-tests/7.4@master
        env:
          MAGENTO_VERSION: '2.4.2'
      - uses: extdn/github-actions-m2/magento-unit-tests/7.4@master
        env:
          MAGENTO_VERSION: '2.4.3-p1'
          COMPOSER_VERSION: '2'
